//DE localization
$.fn.mgVideoChat.translate = {    
    'Your browser does not support websocket.':  'Ihr Browser unterstützt keine WebSocket.',
    'Your browser does not support PeerConnections.':  'Ihr Browser unterstützt keine PeerConnections.',
    'Your browser does not support user media.':  'Ihr Browser unterstützt keine Benutzermedien.',
    'Please try <a href="http://www.google.com/chrome" target="_blank">Google Chrome</a> or <a href="http://www.mozilla.org/en-US/firefox" target="_blank">Mozilla Firefox</a>':  'Bitte versuchen Sie <a href="http://www.google.com/chrome" target="_blank"> Google Chrome </a> oder <a href = "http://www.mozilla.org/en-US / firefox "target =" _blank "> Mozilla Firefox </a>',
    'Callee is busy at the moment, please try later :(':  'Angerufene ist besetzt im Moment, versuchen Sie es später :(',
    'No partner found at the moment. Please try later.':  'Kein Partner in dem Moment gefunden. Bitte versuchen Sie es später.',
    'Error connecting to media server: {error_name} {error_message}':  'Fehler beim Verbinden mit Medienserver: {error_name} {error_message}',
    'Websocket closed, please try reloading page later.':  'WebSocket geschlossen, versuchen Sie es später Nachladen Seite.',
    'Error getting local media stream: {error_message}':  'Fehler beim Abrufen der lokalen Medien Strom: {error_message}',
    'Error creating peer connection: {error_name} {error_message}':  'Fehler beim Erstellen von Peer-Verbindung: {error_name} {error_message}',
    'You and your peer are not using the same browser. File transfer between different browser most likely will not work.':  'Sie und Ihr Peer sind nicht mit der gleichen Browser. Dateitransfer zwischen verschiedenen Browser wahrscheinlich nicht funktionieren wird.',
    'This file size of over maximum defined of {max_size}':  'Dieses Dateigröße von über maximal definiert {max_size}',
    'Send a message':  'Eine Nachricht senden',
    'Text chat':  'Text-Chat',
    'Send a file':  'Senden einer Datei',
    'Call':  'Anruf',
    'Call Audio':  'Call Audio',
    'Answer':  'Antwort',
    'Cancel':  'stornieren',
    'Hang Up':  'auflegen',
    'In call':  'in Call',
    'Users online':  'Benutzer online',
    'No one else here at the moment :(':  'Niemand sonst hier im Moment :(',
    'accept':  'akzeptieren',
    'cancel':  'stornieren',
    'Login':  'Login',
    'Full Screen':  'Vollbild',
    'Exit Full Screen':  'Exit Full Screen',
    'Hang up':  'auflegen (Telefon) / aufhängen',
    'Video Mute':  'Video Mute',
    'Video Un-Mute':  'Video Un-Mute',
    'Audio Mute':  'Audio Mute',
    'Audio Un-Mute':  'Audio Stummschaltung',
    'Chat':  'plaudern',
    'Username':  'Benutzername',
    'Answer with Video':  'Antwort mit Video',
    'Answer Audio':  'Antwort Audio',
    'Access confirmation':  'Zugang Bestätigung',
    '<strong>Heads up!</strong> Please note browser confirmation dialog on top of your window.':'<strong>Kopf hoch!</strong> Bitte beachten Sie Bestätigungsdialog Browser auf Ihre Fenster.',
    'File Offer':  'Datei-Angebot',
    'is offering a file <strong class="fileName"></strong> of <em class="fileSize"></em>':  'bietet eine Datei <strong class = "filename"> </ strong> der <em class = "filesize"> </ em>',
    'Accept file':  'akzeptieren Datei',
    'Reject':  'ablehnen',
    'Roulette partner':  'Roulette Partner',
    'users online':  'Benutzer online',
    'Next':  'nächste',
    'Please enable requested media devices': 'Bitte aktivieren angeforderten Medien-Geräte',
    'Please enable requested media devices by clicking on the right hand icon in the address bar.': 'Bitte aktivieren angeforderten Medien-Geräten, indem Sie auf der rechten Symbol in der Adressleiste.',
    'You':  'Sie',
    'Chat with {username}': 'Chat mit {username}',
    'Group chat': 'Gruppen-Chat',
    'Call with {username}': 'Rufen Sie mit {username}'
}


